name: Submit extension

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Get artifact info
      id: get_artifact_info
      run: |
        echo "::set-output name=fileName::$(ls artifacts | head -n 1)"
    - name: Browser Plugin Publish
      uses: plasmo-corp/bpp@v1
      with:
        artifact: "artifacts/${{ steps.get_artifact_info.outputs.fileName }}"
        keys: ${{ secrets.SUBMIT_KEYS }}